### ISSUE TITLE
懂美味 — 首页出现相同文章两篇。

### ISSUE THREAD

**Issue by jiale888** [haxibiao/dongmeiwei#10]
![image.png](https://images.zenhubusercontent.com/5aab1f764b5806bc2bcb1322/536f5f35-d49a-448f-912b-78d16096caed)

**Comment by jiale888** [comment]
并没有重复发送。

**Comment by wangxinaa** [comment]
那是你发了两篇文章

**Comment by jiale888** [comment]
应该是浏览器崩掉了，不影响。关掉了
