### ISSUE TITLE
懂美味— 抓取的文章不干净

### ISSUE THREAD

**Issue by jiale888** [haxibiao/dongmeiwei#14]
![image.png](https://images.zenhubusercontent.com/5aab1f764b5806bc2bcb1322/d92a1bd0-1f8f-4a50-8e63-fbdeb5a58efc)
需要再次编辑。

**Comment by pengconguses1** [comment]
数据有问题 下次不用这个分类的文章

**Comment by jiale888** [comment]
好哒~~~
