### ISSUE TITLE
懂美味 — 专题收录数目跟实际显示数目不相符。

### ISSUE THREAD

**Issue by jiale888** [haxibiao/dongmeiwei#15]
![image.png](https://images.zenhubusercontent.com/5aab1f764b5806bc2bcb1322/aa11d63c-1933-4383-b55c-382f0bc1862b)
实际只有10篇。

**Comment by jiale888** [comment]
搜狗浏览器问题。360没问题。

**Comment by pengconguses1** [comment]
已查明 浏览器问题  chorme内核系的浏览器没问题
