### ISSUE TITLE
懂美味的tdk

### ISSUE THREAD

**Issue by jiale888** [haxibiao/dongmeiwei#16]
keywords：家常菜谱，合理膳食，菜谱,美食,懂美味，美食问答

descriptio：懂美味-随时分享与点评优质的菜谱与美食，提供美食爱好者一个记录、分享的社交平台。

title：每天分享一点菜谱和美食|懂你的，才是美味。

**Comment by pengconguses1** [comment]
OK 懂美味的已经加上

**Comment by jiale888** [comment]
ok····
