### ISSUE TITLE
懂美味 — 评论可以提交空白内容

### ISSUE THREAD

**Issue by jiale888** [haxibiao/dongmeiwei#17]
![image.png](https://images.zenhubusercontent.com/5aab1f764b5806bc2bcb1322/5aaa4dca-bf21-47f3-95e5-29a2950278eb)
评论可以提交空白内容，刷新就没有了，可否在提交空白内容时，给一个提示：需要输入内容才可以发表或者别的..........，或者直接给一个限制，没有内容，发表按钮就变暗，输入内容，发表按钮就恢复颜色

**Comment by yasin-wang** [comment]
修复了评论组件回复空内容的bug，空白内容时并禁用发送按钮
