### ISSUE TITLE
为懂美味APP准备官方专题

### ISSUE THREAD

**Issue by ivanzhang2** [haxibiao/dongmeiwei#20]
1. 彭聪增加专题3个字段，is_official, is_for_app, logo_app
2. 乐乐准备相应11个app需要显示的专题，app图标找王宇坤
3. 彭聪更新好后端后，提交代码，过来找张总学习如何为这个app需求提供graphql api
4. 王宇坤完成app端调用graphql api .

**Comment by pengconguses1** [comment]
字段已经添加上 老王改一下创建专题的表单~

**Comment by yasin-wang** [comment]
已经完成了

**Comment by jiale888** [comment]
已经完成了八大菜系专题的显示的图标~
